### ISSUE TITLE
Soundfonts that don't convert well

### ISSUE THREAD

**Issue by RogerLevy** [parbo/soundfont-deluge#2]
cargo run -- -a SAMPLES -y SYNTH -p KART -d ../SuperMarioKart.sf2
[super_mario_kart_soundfont.zip](https://github.com/parbo/soundfont-deluge/files/9387602/super_mario_kart_soundfont.zip)

I have a bunch more video game soundfonts I'd like to convert.

**Comment by parbo** [comment]
It should work better now. I had missed that `KeyRange` was optional in a SoundFont. I also found some other bugs that I fixed.

**Comment by RogerLevy** [comment]
That worked!

In a somewhat expected way, one of the samples wasn't linked.  Glockenspiel 2.  I know that that one has a crazy low sample rate of ~2200 which is easily fixed in audacity and can be manually linked in the XML file so maybe that can be considered an edge case, a problem with the soundfont rather than the tool itself?

**Comment by RogerLevy** [comment]
Got another one with all of the samples not being linked
[KirbysDreamLand3.zip](https://github.com/parbo/soundfont-deluge/files/9389382/KirbysDreamLand3.zip)

cargo run -- -a SAMPLES/SNES/KIRBY -y SYNTH/KIRBY -d ../KirbysDreamLand3.sf2

**Comment by parbo** [comment]
I'm not doing any conversion of the samples, just saving them as-is. I noticed the glockenspiel too, but I haven't looked at why it happens.

**Comment by parbo** [comment]
Converting samples to other sample rates would mean having to re-compute all the dependent values like loop positions etc.

**Comment by RogerLevy** [comment]
Yeah, sounds like it's not worth it for the outliers.  That Kirby soundfont doesn't have any weird sample rates as far as I can see.

**Comment by RogerLevy** [comment]
> Converting samples to other sample rates would mean having to re-compute all the dependent values like loop positions etc.

On second thought I don't think you'd have to actually resample or recalculate anything.  In Audacity all I did was change the sample rate setting.  In effect that just made the sample play at a sensible rate.

**Comment by parbo** [comment]
I solved this now. There was two issues, one was that I missed a detail in the SoundFont spec about how root note could be specified, and the other was about unsupported sample rates. I ended up scaling the sample rate to a range that hopefully is supported on the Deluge. I also scale the transposing to counter that.
